### ISSUE TITLE
Unexpected token '('

### ISSUE THREAD

**Issue by xMyThoLoGyx** [SimonLeclere/discord-hangman#4]
No matter where I put hangman = require('discord-hangman')

I get this: 
SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (F:\Discord Bots\The Red Queen\functionnalities\hangmanGame.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)

**Comment by SimonLeclere** [comment]
Hey, can you show me your code ? And also are u hosting on repl.it ?

**Comment by xMyThoLoGyx** [comment]
No I'm working on my home pc, so launching from VSC

const hangman = require ('discord-hangman');
module.exports = {
    name: 'hangmanGame',
    execute(msg, userMessage, client, Discord){
      hangManio();
        
    async function hangManio(){
        await hangman.create(userMessage.channel, 'random', { word: 'doodle' })
    }     
    
    }
}

**Comment by SimonLeclere** [comment]
You use your hangManio function before defining it?

**Comment by xMyThoLoGyx** [comment]
It doesn't give me an error. The problem is, even in my index, if I run await hangman.create(....)

it gives me the same error

**Comment by xMyThoLoGyx** [comment]
Add me on discord, it's easier if I showed you: MyThoLoGy#8718

**Comment by SimonLeclere** [comment]
You can join my discord server if you want https://discord.gg/U2VGrkT

**Comment by SimonLeclere** [comment]
wich node version are u using ?

**Comment by SimonLeclere** [comment]
Resolved (Try to use a node version higher or equal to v14)
